---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.height = 6,
                      fig.width = 8)

library(tidyverse)
library(plotly)
library(p8105.datasets)
```


```{r}
data("rest_inspec")

res_insp <- rest_inspec %>% 
  janitor::clean_names() %>% 
  drop_na()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
res_insp %>% 
  filter(boro == "MANHATTAN") %>% 
  separate(inspection_date, c("year", "month", "day"),sep = "-") %>% 
  select(boro, year, score) %>% 
  mutate(text_label = str_c("Borough: ", boro)) %>% 
  plot_ly(y = ~score, color = ~year, text = ~text_label, type = "box",
          colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
res_insp %>% 
  filter(grade %in% c("A", "B", "C"),
         cuisine_description == "American") %>% 
  mutate(text_label =  str_c("Cuisine type: ", cuisine_description)) %>% 
  group_by(boro, grade, text_label) %>% 
  summarise(count = n()) %>% 
  plot_ly(x = ~boro, y = ~count, color = ~grade, text = ~text_label, type = "bar")
```

### Chart C

```{r}
res_insp %>% 
  filter(boro == "MANHATTAN") %>% 
  group_by(inspection_date) %>% 
  summarise(count = n()) %>% 
  select(inspection_date, count) %>%
  plot_ly(x = ~inspection_date, y = ~count, type = "scatter", mode = "lines",
          fill = "tozeroy")
```

